version: "2"
services:
  pointofdelivery:
    image: openlmis/dev:7
    ports:
      - "5005:5005"
      - "8080:8080"
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
    env_file: .env
volumes:
  gradlecache:
    external: false
