version: "2"
services:

  prepacking:
    image: openlmis/prepacking
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres:12-debezium
    ports:
      - "5432"
    env_file: .env

  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/prepacking:/var/log'
